return {
  "ibhagwan/fzf-lua",
  dependencies = { "echasnovski/mini.icons" },
  opts = {
    winopts = {
      height = 0.90,
      width = 0.95,
      preview = {
        layout = "flex",
        vertical = "down:50%",
        horizontal = "right:50%",
      },
    },
    fzf_opts = {
      ["--layout"] = "reverse", -- prompt on top (similar to prompt_position = "top")
    },
    files = {
      fd_opts = table.concat({
        "--color=never",
        "--type",
        "f",
        "--hidden",
        "--follow",
        "--exclude",
        ".git/",
        "--exclude",
        "tmp/",
        "--exclude",
        "dryrun/",
        "--exclude",
        "node_modules/",
        "--exclude",
        "target/",
        "--exclude",
        "__pycache__/",
        "--exclude",
        ".pytest_cache/",
        "--exclude",
        "build/",
        "--exclude",
        ".bemol/",
        "--exclude",
        ".brazil/",
        "--exclude",
        "release-info/",
        "--exclude",
        "env/",
        "--exclude",
        ".settings/",
        "--exclude",
        "logs/",
        "--exclude",
        "versionSets/",
        "--exclude",
        ".ignore",
        "--exclude",
        "packageInfo",
        "--exclude",
        "packageInfo.bak",
        "--exclude",
        ".gradle",
      }, " "),
      formatter = "path.filename_first",
    },
    grep = {
      rg_opts = table.concat({
        "--color=never",
        "--no-heading",
        "--with-filename",
        "--line-number",
        "--column",
        "--smart-case",
        "--hidden",
        "--follow",
        "--glob=!**/.git/*",
        "--glob=!**/tmp/*",
        "--glob=!**/dryrun/*",
        "--glob=!**/node_modules/*",
        "--glob=!**/target/*",
        "--glob=!**/__pycache__/*",
        "--glob=!**/.pytest_cache/*",
        "--glob=!**/build/*",
        "--glob=!**/.bemol/*",
        "--glob=!**/.brazil/*",
        "--glob=!**/release-info/*",
        "--glob=!**/env/*",
        "--glob=!**/.settings/*",
        "--glob=!**/logs/*",
        "--glob=!**/versionSets/*",
        "--glob=!**/.ignore",
        "--glob=!**/packageInfo",
        "--glob=!**/packageInfo.bak",
        "--glob=!**/.gradle/*",
      }, " "),
      formatter = "path.filename_first",
    },
  },
}
